version: '3.9'

services:
  backend:
    image: anory-backend:1.0
    working_dir: /var/www/html
    volumes:
      - ./backend/:/var/www/html

  frontend:
    image: anory-frontend:1.0
    working_dir: /var/www/html
    volumes:
      - ./frontend:/var/www/html

  proxy:
    image: anory-proxy:1.0
    ports:
      - 8000:80
    volumes:
      - ./proxy/:/var/www/html
      # postgres:
      # image: postgres:14.3-alpine
      # volumes:
      #   - ./db:/app
      # environment:
      # - POSTGRES_PASSWORD=secretsecret
