version: '3.9'

services:
  postgres:
    image: postgres:14.3-bullseye
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secretsecret

  backend:
    image: anory-backend:1.0
    working_dir: /var/www/html
    depends_on:
      - "postgres"

  frontend:
    image: anory-frontend:1.0
    working_dir: /var/www/html

  proxy:
    image: anory-proxy:1.0
    ports:
      - 8000:80
    depends_on:
      - "backend"
      - "frontend"
      - "postgres"
