version: '3.9'

services:
  backend:
    image: laravel-alpine:latest
    working_dir: /var/www/html
    volumes:
      - ./backend/:/var/www/html

  proxy: 
    image: proxyr:latest
    ports:
      - 8000:80
    volumes:
      - ./backend/:/var/www/html

  # frontend:
    # image: anory-frontend:1.0
    # ports:
      # - 4173:4173
    # working_dir: /app
    # volumes:
    #   - ./frontend:/app

  # postgres:
    # image: postgres:14.3-alpine
    # volumes:
    #   - ./db:/app
    # environment:
      # - POSTGRES_PASSWORD=secretsecret
